### ISSUE TITLE
testing got wrong with ci-info

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/wechaty-puppet-official-account#8]
refer to : https://github.com/wechaty/wechaty-puppet-official-account/runs/1308782369?check_suite_focus=true

It seems that `sendCustomMessage` unit test can't skip `pr`, so it remains wrong with `Github Actions`.  And more, **only** the `sendCustomMessage` unit test can't skip `pr` runtime test.

**Comment by huan** [comment]
The unit test will send a message to my WeChat account, so I have just sent a message to the OA account which was used by the unit test. 

The GitHub Action should be passed this time, let's see.

**Comment by wj-Mcat** [comment]
Cherrs.  🍻
